crowdfunding/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^crowdfunding/$', views.crowdfunding, name='crowdfunding'),
    url(r'^crowdfunding/latest/proposals/$', views.latest_crowdfunding_proposals, name='crowdfunding_latest_proposals'),
    url(r'^crowdfunding/closed/proposals/$', views.closed_crowdfunding_proposals, name='crowdfunding_closed_proposals'),
    url(r'^crowdfunding/votedbyme/proposals/$', views.voted_crowdfunding_proposals, name='crowdfunding_voted_proposals'),
    url(r'^crowdfunding/close_proposal/$', views.close_proposal, name='crowdfunding_close_proposal'),
    url(r'^crowdfunding/rejection_proposal/$', views.rejection_proposal, name='crowdfunding_rejection_proposal'),
    url(r'^crowdfunding/new/$', views.create_crowdfunding, name='create_crowdfunding'),
    url(r'^crowdfunding/user_creation/$',views.user_creation,name='user_creation'),
    url(r'^crowdfunding/facilitators/$',views.crowdfunding_facilitators,name='crowdfunding_facilitators'),
    url(r'^crowdfunding/members/$',views.crowdfunding_members,name='crowdfunding_members'),
    url(r'^crowdfunding/user/(?P<pk>\d+)/$',views.crowdfunding_user_details,name='crowdfunding_user_details'),
    url(r'^crowdfunding/edit/(?P<pk>\d+)/$',views.crowdfunding_edit_user,name='crowdfunding_edit_user'),
    url(r'^crowdfunding/(?P<pk>\d+)/$', views.crowdfunding_detail, name='crowdfunding_detail'),
    url(r'^crowdfunding/vote/$', views.crowdfunding_vote, name='crowdfunding_vote'),
    url(r'^crowdfunding/get_group_total_amount/$', views.get_group_total_amount, name='get_group_total_amount'),
    url(r'^crowdfunding/post_comment/$', views.post_comment, name='post_comment'),
    url(r'^crowdfunding/get_user_private_key/$', views.get_user_private_key, name='get_user_private_key'),
    url(r'^crowdfunding/make_history/$', views.make_history, name='make_history'),
    
    # url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.login, name='login'),
    url(r'^ajax/validate_username/$', views.validate_username, name='validate_username'),
    url(r'^signout/$', auth_views.logout, {'next_page': '/'}, name='signout'),
]

pyethweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('login.urls')),
    url(r'',include('crowdfunding.urls',namespace='crowdfunding')),
]

crowdfunding/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from simple_history.models import HistoricalRecords

class CrowdFundingMemberGroup(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class UserExtendedForFunding(models.Model):

    USER_TYPE = [('FR', "Facilitator"), ('MR', "Member"),]
    FUNDING_TYPE =[('MR',"MemberFunding"),('GR',"GroupFunding"),]
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_extented')
    funding_amout = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    group_type = models.ForeignKey(CrowdFundingMemberGroup, blank=True, null=True)
    user_type = models.CharField(max_length=2,
        choices=USER_TYPE, blank=True
    )
    user_image = models.ImageField(upload_to = 'image/', blank=True)
    funding_type = models.CharField(max_length=2,
        choices=FUNDING_TYPE, blank=True
        )
    ether_account_private_key = models.CharField(max_length=200, blank=True, null=True)
    history = HistoricalRecords()

class CrowdFundingProposalSettings(models.Model):
    proposal_success_perc = models.IntegerField()
    history = HistoricalRecords()

class CrowdFundingPostProposal(models.Model):

    # STATE = [('DT', "Draft"), ('CD', "Closed"),]
    STATE = [('DT', "Draft"), ('CD', "Closed"), ('RJ', "Rejection"),]
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    amount = models.DecimalField(max_digits=5, decimal_places=2)
    created_datetime = models.DateTimeField(
            default=timezone.now)
    published_datetime = models.DateTimeField(
            blank=True, null=True)
    end_date = models.DateField(
            blank=True, null=True)
    state = models.CharField(max_length=2,
        choices=STATE, default='DT'
    )
    group_type = models.ForeignKey(CrowdFundingMemberGroup, blank=True, null=True)
    up_count = models.IntegerField(default=0)
    down_count = models.IntegerField(default=0)
    history = HistoricalRecords()

    def publish(self):
        self.published_datetime = timezone.now()
        self.save()

    def __str__(self):
        return self.title


class CrowdFundingProposalVoting(models.Model):
    UP = 'UP'
    DOWN = 'DN'
    VOTE_TYPE = [(UP, "Upvote"), (DOWN, "DownVote")]
    author = models.ForeignKey('auth.User')
    created_datetime = models.DateTimeField(
            default=timezone.now)
    vote_type = models.CharField(max_length=2,
        choices=VOTE_TYPE, blank=True

    )
    proposal_id = models.ForeignKey(CrowdFundingPostProposal, models.SET_NULL, blank=True, null=True)
    history = HistoricalRecords()

    def __str__(self):
        return 'Proposal={0}: Auther={1}'.format(self.proposal_id, self.author)

class Comment(models.Model):
    proposal_id = models.ForeignKey(CrowdFundingPostProposal, models.SET_NULL, blank=True, null=True)
    author = models.ForeignKey('auth.User')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    history = HistoricalRecords()

    def __str__(self):
        return self.text

crowdfunding/forms.py
from django import forms
from .models import CrowdFundingPostProposal, Comment
from django.contrib.auth.models import User

class CrowdFundingPostProposalForm(forms.ModelForm):

    class Meta:
        model = CrowdFundingPostProposal
        fields = ('title', 'text','amount', 'end_date')

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

crowdfunding/views.py
from django.contrib.auth.decorators import login_required
from .models import CrowdFundingMemberGroup, CrowdFundingMemberGroup, UserExtendedForFunding, CrowdFundingPostProposal, CrowdFundingProposalVoting, Comment
from django.contrib.admin.models import LogEntry, ADDITION, CHANGE
from .forms import CrowdFundingPostProposalForm, UserForm
from django.shortcuts import redirect, get_object_or_404, render
from django.utils import timezone
from django.http import JsonResponse, HttpResponse, HttpResponsePermanentRedirect
from django.db.models import Sum
# from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from login.forms import RegistrationForm
from django.contrib.auth.models import User
from django.core import serializers
from django.contrib.contenttypes.models import ContentType
from django.forms.models import inlineformset_factory

# Create your views here.

@login_required(login_url='/')
def crowdfunding(request):
    group_type = CrowdFundingMemberGroup.objects.all()
    latest_posts = CrowdFundingPostProposal.objects.filter(published_datetime__lte=timezone.now(), state='DT').order_by('published_datetime')
    # closed_posts = CrowdFundingPostProposal.objects.filter(published_datetime__lte=timezone.now(), state='CD').order_by('published_datetime')
    closed_posts = CrowdFundingPostProposal.objects.filter(published_datetime__lte=timezone.now()).exclude(state='DT').order_by('published_datetime')
    closed_len = len(closed_posts)
    latest_len = len(latest_posts)
    facilitator_count = UserExtendedForFunding.objects.filter(user_type='FR').count()
    member_count = UserExtendedForFunding.objects.filter(user_type='MR').count()
    voted_by_me_count = CrowdFundingProposalVoting.objects.filter(author=request.user).count()
    return render(request, 'crowdfunding/crowdfunding_home.html', {'posts':latest_posts, 'member_count':member_count, 'facilitator_count':facilitator_count, 'latest_len':latest_len, 'closed_len':closed_len, 'closed_posts':closed_posts, 'group_type':group_type, 'voted_by_me_count':voted_by_me_count})

@login_required(login_url='/')
def latest_crowdfunding_proposals(request):
    group_type = CrowdFundingMemberGroup.objects.all()
    latest_posts_list = CrowdFundingPostProposal.objects.filter(published_datetime__lte=timezone.now(), state='DT').order_by('published_datetime')
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    latest_paginator = Paginator(latest_posts_list, 4, request=request)
    latest_posts = latest_paginator.page(page)
    # latest_paginator = Paginator(latest_posts_list, 1)
    #
    # page = request.GET.get('page')
    # try:
    #     latest_posts = latest_paginator.page(page)
    # except PageNotAnInteger:
    #     # If page is not an integer, deliver first page.
    #     latest_posts = latest_paginator.page(1)
    # except EmptyPage:
    #     # If page is out of range (e.g. 9999), deliver last page of results.
    #     latest_posts = latest_paginator.page(latest_paginator.num_pages)

    # upvote = CrowdFundingPostProposal.objects.filter(crowdfundingproposalvoting__vote_type='UP').count()
    # downvote = CrowdFundingPostProposal.objects.filter(crowdfundingproposalvoting__vote_type='DN').count()
    print latest_posts, " <--------------------------------"
    return render(request, 'crowdfunding/crowdfunding_proposals.html', {'posts':latest_posts, 'group_type':group_type, 'title':'Active Proposals'})

def voted_crowdfunding_proposals(request):
    voted_posts_list = CrowdFundingProposalVoting.objects.filter(author=request.user)
    self_user_proposal_list = [x.proposal_id for x in voted_posts_list]
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    voted_paginator = Paginator(self_user_proposal_list, 4, request=request)
    self_user_proposal = voted_paginator.page(page)
    return render(request, 'crowdfunding/crowdfunding_proposals.html', {'posts':self_user_proposal, 'title':'Voted Proposals'})

@login_required(login_url='/')
def closed_crowdfunding_proposals(request):

    group_type = CrowdFundingMemberGroup.objects.all()
    # closed_posts_list = CrowdFundingPostProposal.objects.filter(published_datetime__lte=timezone.now(), state='CD').order_by('published_datetime')
    closed_posts_list = CrowdFundingPostProposal.objects.filter(published_datetime__lte=timezone.now()).exclude(state='DT').order_by('published_datetime')
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    closed_paginator = Paginator(closed_posts_list, 4, request=request)
    closed_posts = closed_paginator.page(page)


    # closed_paginator = Paginator(closed_posts_list, 4)
    # page = request.GET.get('page')
    # try:
    #     closed_posts = closed_paginator.page(page)
    # except PageNotAnInteger:
    #     # If page is not an integer, deliver first page.
    #     closed_posts = closed_paginator.page(1)
    # except EmptyPage:
    #     # If page is out of range (e.g. 9999), deliver last page of results.
    #     closed_posts = closed_paginator.page(closed_paginator.num_pages)
    return render(request, 'crowdfunding/crowdfunding_proposals.html', {'posts':closed_posts, 'group_type':group_type, 'title':'Closed Proposals'})

@login_required(login_url='/')
def create_crowdfunding(request):
    # print "-----------------------> ", request.POST
    if request.method == "POST":
        form = CrowdFundingPostProposalForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_datetime = timezone.now()
            post.save()
        return redirect('/')
    else:
        form = CrowdFundingPostProposalForm()
    return redirect('/')

@login_required(login_url='/')
def user_creation(request):
    if request.method == "POST":
        if request.POST.get('type') == 'create-user':
            request.POST = request.POST.copy()
            request.POST['repeat_password'] = request.POST.get('password')

            form = RegistrationForm(request.POST)
            if form.is_valid():
                user = User.objects.create_user(
                    username=form.cleaned_data['username'],
                    password=form.cleaned_data['password'],
                    email=form.cleaned_data['email'],
                )
                user_type = 'FR' if request.POST.get('user_type')=='FR' else 'MR'
                funding_type = 'MR' if request.POST.get('funding_type')=='MR' else 'GR'
                u_extended = UserExtendedForFunding(user=user, user_type=user_type,funding_type=funding_type, user_image=request.FILES.get('user_image'), funding_amout=100.00, ether_account_private_key=request.POST.get('private_key'))
                u_extended.save()
    return redirect('/')

@login_required(login_url='/')
def crowdfunding_detail(request, pk):
    post = get_object_or_404(CrowdFundingPostProposal, pk=pk)
    upvote = CrowdFundingPostProposal.objects.filter(crowdfundingproposalvoting__vote_type='UP', pk=pk).count()
    downvote = CrowdFundingPostProposal.objects.filter(crowdfundingproposalvoting__vote_type='DN', pk=pk).count()
    comments = Comment.objects.filter(proposal_id__exact=pk)
    return render(request, 'crowdfunding/post.html', {'post': post, 'upvote':upvote, 'downvote':downvote, 'comments':comments})

@login_required(login_url='/')
def crowdfunding_vote(request):
    post_id = request.GET.get('post_id', None)
    vote_type = request.GET.get('vote_type', None)
    proposal = CrowdFundingPostProposal.objects.get(pk=post_id)
    success = False
    # self_user_proposal = CrowdFundingPostProposal.objects.filter(crowdfundingproposalvoting__author=request.user, pk=post_id)
    if request.user.user_extented.user_type == 'MR':
        self_proposal = CrowdFundingPostProposal.objects.filter(id=post_id)
        self_user_voting = CrowdFundingProposalVoting.objects.filter(proposal_id__exact=post_id, author=request.user)
        if self_user_voting:
            if self_user_voting[0].vote_type == 'UP' and vote_type == 'DN':
                if (proposal.down_count == 0 and proposal.up_count == 0) or (proposal.down_count > 0 and proposal.up_count == 0):
                    down_count = proposal.down_count + 1
                    self_proposal.update(down_count= down_count)
                elif (proposal.down_count == 0 and proposal.up_count > 0) or (proposal.down_count > 0 and proposal.up_count > 0):
                    up_count = proposal.up_count - 1
                    down_count = proposal.down_count + 1
                    self_proposal.update(down_count= down_count, up_count= up_count)
                self_user_voting.update(vote_type='DN')
                success = True
            elif self_user_voting[0].vote_type == 'DN' and vote_type == 'UP':
                if (proposal.up_count == 0 and proposal.down_count == 0) or (proposal.up_count > 0 and proposal.down_count == 0):
                    up_count = proposal.up_count + 1
                    self_proposal.update(up_count= up_count)
                if (proposal.up_count == 0 and proposal.down_count > 0) or (proposal.up_count > 0 and proposal.down_count > 0):
                    up_count = proposal.up_count + 1
                    down_count = proposal.down_count - 1
                    self_proposal.update(down_count= down_count, up_count= up_count)
                self_user_voting.update(vote_type='UP')
                success = True
        else:
            # if not self_user_voting.exists():
            if vote_type == 'UP':
                up_count = proposal.up_count + 1
                self_proposal.update(up_count= up_count)
            elif vote_type == 'DN':
                down_count = proposal.down_count + 1
                self_proposal.update(down_count= down_count)

crowdfunding/templates/crowdfunding/crowdfunding_home.html
{% extends 'crowdfunding/crowdfunding.html' %}

{% load staticfiles %}
{% block body_content %}
<style>
    .dash-title-1{position: absolute;top:24%;left: 36%;font-size: 20px;color: #fff;}
    .dash-text-1{position: absolute;top:32%;left: 33%;font-size: 24px;color: #563b28;text-transform: uppercase;font-weight: 500;}
    .dash-number-1{position: absolute;top:54%;left: 45%;font-size: 31px;color: #563b28;text-transform: uppercase;font-weight: 500;}
    
    .dash-title-2{position: absolute;top:24%;left: 35%;font-size: 20px;color: #fff;}
    .dash-text-2{position: absolute;top:32%;left: 29%;font-size: 24px;color: #563b28;text-transform: uppercase;font-weight: 500;}
    .dash-number-2{position: absolute;top:54%;left: 45%;font-size: 31px;color: #563b28;text-transform: uppercase;font-weight: 500;}
    
    .dash-title-3{position: absolute;top:12%;left: 45%;font-size: 18px;color: #c3996b;}
    .dash-text-3{position: absolute;top:32%;left: 37%;font-size: 20px;color: #fff;text-transform: uppercase;font-weight: 500;}
    .dash-number-3{position: absolute;top:64%;left: 51%;font-size: 31px;color: #563b28;text-transform: uppercase;font-weight: 500;}
    
    .dash-title-4{position: absolute;top:12%;left: 34%;font-size: 18px;color: #c3996b;}
    .dash-text-4{position: absolute;top:32%;left: 26%;font-size: 20px;color: #fff;text-transform: uppercase;font-weight: 500;}
    .dash-number-4{position: absolute;top:66%;left: 40%;font-size: 31px;color: #563b28;text-transform: uppercase;font-weight: 500;}
    
    .dash-bor-right{border-right: 2px solid #c49a6c;}
    .img-vote{position: absolute; top:93%;left: 39%;}
    .vote-text{position: absolute; top:44%;left: 49%;z-index:1;font-size: 31px;}
    .vote-txt{position: absolute; top:35%;left: 45%;color: #292115;z-index:1;font-size: 19px;}
    .vote-f1{left:42%!important;}
    /*media query starts*/
    @media screen and (min-width: 1400px) and (max-width: 1920px) {
    

.img-vote{top: 27%;left: 42%;}
    

.vote-text{top: 37%;left: 49%;}
    

}
    
    

@media screen and (min-width: 601px) and (max-width: 768px) {
    

.img-vote{top: 112%;left: 28%;}
    

.vote-text{top: 123%;left: 46%;}
 .vote-f1{left:37%!important;} 

}
    
 @media screen and (min-width: 601px) and (max-width: 1000px) {
          .vote-txt{left: 40%;}    
           .vote-f1{left:37%!important;} 
}


@media screen and (max-width: 600px) {
    

.img-vote{top: 133%;left: 28%;}
    

.vote-text{top: 148%;left: 51%;}
    .vote-txt{left: 40%;}    


}
    
    

@media screen and (max-width: 500px) {
    

.dash-title-1{left: 34%;top: 24%;}
    

.dash-text-1{left:30%;}
    

.dash-number-1{left: 45%;}
    

.dash-title-2{left: 34%;top: 24%;}
    

.dash-text-2{left:26%;}
    

.dash-number-2{left: 45%;}
    

.dash-title-3{top: 6%;left: 40%;font-size: 15px;}
    

.dash-text-3{top: 31%;left: 32%;font-size: 16px;}
    

.dash-number-3{top: 61%;left: 50%; font-size: 20px;}
    

.dash-title-4{top: 6%;left: 32%;font-size: 15px;}
    

.dash-text-4{top: 31%;left: 18%;font-size: 16px;}
    

.dash-number-4{top: 65%;left: 45%; font-size: 20px;}
    

.img-vote{top: 129%; left: 2%;}
    

.vote-text {left: 47%;}
    
.vote-txt{left: 35%;}
.vote-f1{left:25%!important;}
} 

</style>

<div style="margin-top:10px;"></div>
<section>
    <div class="container">
        <div class="row">
            {% if user.is_superuser %}
                <div class="col-md-4 text-center" style="left:6px;">
                    <a href="{% url 'crowdfunding:crowdfunding_members' %}"><img src="../static/images/circle1.png" alt="Smiley face" height="349" width="345" class="img-responsive" style="display:inline-block;"></a>
                    
                    <!-- <div class="dash-title-1">Number of</div> -->
                    <!-- <div class="dash-text-1">Members</div> -->
                    <div class="dash-number-1">{{ member_count }}</div>
                </div>
                 <div class="col-md-4 text-center">
                    <div class="">
                        <img src="../static/images/admin-image2.png" alt="Smiley face" height="353" style="display: inline-block;" class="img-responsive">
                        <!-- <a class="vote-txt" href="{% url 'crowdfunding:crowdfunding_voted_proposals' %}" class="border-tab">Voted By Me</a> -->
                        <!-- <div class="vote-text" style="top:35%; left:25%;"><img src="{% static 'images/admin.jpg' %}" alt=" " width="150" height="150"/></div>  -->
                    </div>
                </div>
                <div class="col-md-4 text-center">
                    <a href="{% url 'crowdfunding:crowdfunding_facilitators' %}"><img src="../static/images/circle2.png" alt="Smiley face" height="349" width="345" class="img-responsive" style="display:inline-block;"></a>
                    <!-- <div class="dash-title-2">Number of</div> -->
                    <!-- <div class="dash-text-2">facilitators</div> -->
                    <div class="dash-number-2">{{ facilitator_count }}</div>
                </div>  

                <div class="clearfix"></div>
                <div class="col-md-6 text-center">
                    <img src="../static/images/new-proposal-left.png" alt="Smiley face" height="207" style="display: inline-block;" class="img-responsive">
                    <div class="dash-title-3">Number of</div>
                    <a class="dash-text-3" href="{% url 'crowdfunding:crowdfunding_latest_proposals' %}" class="border-tab">Active Proposals</a>
                    <div class="dash-number-3">{{ latest_len }}</div>
                </div>  
                <div>
                <div class="col-md-6 text-center">
                    <img src="../static/images/closed-proposal-right.png" alt="Smiley face" height="207" style="display: inline-block;" class="img-responsive">
                    <div class="dash-title-4">Number of</div>
                    <a class="dash-text-4" href="{% url 'crowdfunding:crowdfunding_closed_proposals' %}" class="border-tab">Closed Proposals</a>
                    <div class="dash-number-4">{{ closed_len }}</div>
                </div>
                <div class="clearfix"></div>
               
            {% endif %}
            {% if user.user_extented.user_type == 'FR' %}
                <div class="col-md-12 text-center" style="top:46%; z-index: 111;">
                    <a href="{% url 'crowdfunding:crowdfunding_members' %}"><img src="../static/images/vote.png" alt="Smiley face" height="353" style="display: inline-block;" class="img-responsive"></a>
                    <div class="vote-txt vote-f1" style="top:34%; font-size: 20px;" class="border-tab">Number of Members</div>
                    <div class="vote-text" style="top:44%; left:49%">{{ member_count }}</div> 
                </div> 
                <div class="clearfix"></div>
                <div class="col-md-6 text-center">
                    <img src="../static/images/new-proposal-left.png" alt="Smiley face" height="207" style="display: inline-block;" class="img-responsive">
                    <div class="dash-title-3">Number of</div>
                    <a class="dash-text-3" href="{% url 'crowdfunding:crowdfunding_latest_proposals' %}" class="border-tab">Active Proposals</a>
                    <div class="dash-number-3">{{ latest_len }}</div>
                </div> 
                
                <div class="col-md-6 text-center">
                    <img src="../static/images/closed-proposal-right.png" alt="Smiley face" height="207" style="display: inline-block;" class="img-responsive">
                    <div class="dash-title-4">Number of</div>
                    <a class="dash-text-4" href="{% url 'crowdfunding:crowdfunding_closed_proposals' %}" class="border-tab">Closed Proposals</a>
                    <div class="dash-number-4">{{ closed_len }}</div>
                </div>
            {% endif %}
            {% if user.user_extented.user_type == 'MR' %}
                <div class="clearfix"></div>
                <div class="col-md-12 text-center">
                    <img src="../static/images/vote.png" alt="Smiley face" height="353" style="display: inline-block;" class="img-responsive">
                    <a class="vote-txt" href="{% url 'crowdfunding:crowdfunding_voted_proposals' %}" class="border-tab">Voted By Me</a>
                    <div class="vote-text" style="top:46%">{{ voted_by_me_count }}</div>
                <!--     <body style="margin: 0px;"><img style="-webkit-user-select: none" src="http://www.clipartsmania.com/gif/arrows_gif/arrows_buttom_animation_clipart.gif"></body> -->
                </div>
                <div class="col-md-6 text-center">
                    <img src="../static/images/new-proposal-left.png" alt="Smiley face" height="207" style="display: inline-block;" class="img-responsive">
                    <div class="dash-title-3">Number of</div>
                    <a class="dash-text-3" href="{% url 'crowdfunding:crowdfunding_latest_proposals' %}" class="border-tab">Active Proposals</a>
                    <div class="dash-number-3">{{ latest_len }}</div>
                </div>  
                <div class="col-md-6 text-center">
                    <img src="../static/images/closed-proposal-right.png" alt="Smiley face" height="207" style="display: inline-block;" class="img-responsive">
                    <div class="dash-title-4">Number of</div>
                    <a class="dash-text-4" href="{% url 'crowdfunding:crowdfunding_closed_proposals' %}" class="border-tab">Closed Proposals</a>
                    <div class="dash-number-4">{{ closed_len }}</div>
                </div>
                
            {% endif %}
        </div>
    </div>
</section>  
<br><br><br>
{% endblock %}

crowdfunding/templates/crowdfunding/crowdfunding_user_details.html
{% extends 'crowdfunding/crowdfunding.html' %}

{% load staticfiles %}
{% block body_content %}
<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-md-offset-2 col-md-10">
            <h1>User</h1>
        </div>
        <div class="clearfix"></div>
        <hr/>
        <div class="col-md-4 col-md-offset-2">
            {% if user_details.user_extented.user_image %}
                <img src="{{ user_details.user_extented.user_image.url }}"  alt="Person" width="100%" height="350" style="border-radius: 50px;"/>
            {% else %}
                <img src="{% static 'images/img_avatar.png' %}" alt="Person" width="100%" height="350" style="border-radius: 50px;"/>
            {% endif %}

        </div>
        <div class="col-md-4">
            {% if user.is_superuser %}
                <div class="text-right">
                    <a class="btn btn-default" href="{% url 'crowdfunding:crowdfunding_edit_user' pk=user_details.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                </div>
            {% endif %}
            <div class="form-group">
              <label for="name">Name:</label>
              <input type="text" class="form-control" id="name" placeholder="Enter Name" value="{{ user_details.username }}" readonly>
            </div>
             <div class="form-group">
              <label for="email">Email:</label>
              <input type="email" class="form-control" id="email" placeholder="Enter E-mail" value="{{ user_details.email }}" readonly>
            </div>
              <!--<div class="form-group">-->
                <!--<label for="pwd">Password:</label>-->
                <!--<input type="password" class="form-control" id="pwd">-->
              <!--</div>-->
            {% if user.is_superuser %}
             <div class="form-group">
              <label for="key">Personal key:</label>
              <input type="text" class="form-control" id="key" placeholder="Personal Key" value="{{ user_details.user_extented.ether_account_private_key }}" readonly>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<hr>

{% endblock %}